### ISSUE TITLE
Tennis Weight

### ISSUE THREAD

**Issue by Justinfungi** [ameynarwadkar/Tennis-Analysis-System#1]
hiii your work is super amazing, is it possible to get you weight of tennis

**Comment by ameynarwadkar** [comment]
Sure! Here you can get the weights file: 
https://drive.google.com/file/d/1kiuDHIvO2L8HVDi12YHtovxC3203jQ7t/view?usp=sharing

I used YOLOv8 and trained it on this dataset: 
https://universe.roboflow.com/cvprojects-lpfvk/tennis-ball-detection-ekjow
Regards.

**Comment by Justinfungi** [comment]
> Sure! Here you can get the weights file: https://drive.google.com/file/d/1kiuDHIvO2L8HVDi12YHtovxC3203jQ7t/view?usp=sharing
> 
> I used YOLOv8 and trained it on this dataset: https://universe.roboflow.com/cvprojects-lpfvk/tennis-ball-detection-ekjow Regards.

That is amazing and reli kind of you, and how about the weight to detect the court, is it trained on resnet
